MODULE VARIABLES

 PARAMETER(BOLTZ=1.3806E-23,AVAGD=6.02214E+23,PI=3.141592654,SPI=SQRT(PI))
 INTEGER,DIMENSION(:),ALLOCATABLE 			         :: SP_GRP,SP_NA
 INTEGER 							 :: NSMP,MOVT,LVL,SE_Prev,NCX_OA,NCY_OA
 INTEGER,DIMENSION(:),ALLOCATABLE 				 :: NCOL
 INTEGER,DIMENSION(:),ALLOCATABLE 				 :: CAR,CAB
 DOUBLE PRECISION						 :: KNCC,CHARLEN,TOL
 DOUBLE PRECISION						 :: Vnor,Vtan,Vres
 DOUBLE PRECISION						 :: SI,CO

			! VARIABLES FOR PARALLELIZATION
 INTEGER							 :: rank, nprocs, ierr
 INTEGER							 :: Sdata,Ssize,Sour,destin,Tag,Rdata,Rsize
 INTEGER, DIMENSION(:),ALLOCATABLE				 :: SD_C,SD_N
 DOUBLE PRECISION						 :: CB(6)
 DOUBLE PRECISION						 :: H_SD,W_SD,VOL_SD
 DOUBLE PRECISION						 :: CW_SD,CH_SD
 DOUBLE PRECISION, DIMENSION(:,:,:),ALLOCATABLE	                 :: PACKS,PACKR
 DOUBLE PRECISION						 :: Sdata1,Rdata1
 
 
 INTEGER							 :: NC_SD,NSC_SD,NCX_SD,NCY_SD
 INTEGER							 :: SC(2),RC(2)
 INTEGER							 :: CountTr
 
			! VARIABLES FOR CONSTANTS
 INTEGER, DIMENSION(:),ALLOCATABLE				 :: MSTAT,MJETS
 INTEGER 							 :: REFLAG,SE,RMV,ENT
 DOUBLE PRECISION						 :: XC,YC,AT
 INTEGER,DIMENSION(:),ALLOCATABLE				 :: FLAG
 
 			! VARIABLES FOR DOMAIN DEFINITION
 INTEGER							 :: BC(6)
 DOUBLE PRECISION						 :: OB(6)
 
 			! VARIABLES FOR GRID DEFINITION
 DOUBLE PRECISION						 :: H_D,W_D,D_D,VOL_D
 DOUBLE PRECISION						 :: CW,CH
 INTEGER							 :: NC_D,NC_OLD,NCX_D,NCY_D
 INTEGER							 :: NSC_D,NSCX,NSCY 
INTEGER								 ::ADPMAXLVL,ADP!added for adp	
	
 INTEGER				                         :: NC_MAX,NSC_MAX
INTEGER,DIMENSION(:),ALLOCATABLE		                 :: CE,CELLPOP
!ORTHOGONAL GRID
 DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE		         :: CG,CGN
 DOUBLE PRECISION,DIMENSION(:),ALLOCATABLE		         :: CC,CT
 
  			! VARIABLES FOR STREAM DEFINITION
 INTEGER 						         :: NSP_D,NSP_T,Bod
 DOUBLE PRECISION						 :: FND_D,TMP_D  			
 DOUBLE PRECISION,DIMENSION(:),ALLOCATABLE		         :: FSP_D
 
		 ! VARIABLES FOR MOLECULE DISTRIBUTION 
 INTEGER 						         :: NM
 INTEGER,DIMENSION(:),ALLOCATABLE				 :: NMO,IP,ISC
 DOUBLE PRECISION						 :: VMP
 DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE		         :: PP
 
  			! VARIABLES FOR SIM. PARAMETERS
 INTEGER 							 :: NPR
 INTEGER,DIMENSION(:),ALLOCATABLE				 :: NTS,BD
 INTEGER 							 :: NSIM
 DOUBLE PRECISION 						 :: FNUM,DTM
 
			! VARIABLES FOR CHECKLIST PARAMETERS
 INTEGER,DIMENSION(:),ALLOCATABLE 				 :: Check

 			! VARIABLES FOR JET DEFINITION
 INTEGER							 :: NJET
 INTEGER,DIMENSION(:),ALLOCATABLE 				 :: NSP_J
 CHARACTER(20),DIMENSION(:),ALLOCATABLE 			 :: DESC_J
 CHARACTER(10),DIMENSION(:),ALLOCATABLE 			 :: PROF_J
 DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE		         :: JET,SP_FRJ,VP_J,ENT_J,REM_J
 DOUBLE PRECISION,DIMENSION(:),ALLOCATABLE 		         :: TMP_J,FND_J
 DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE		         :: A_con,B_con,C_con
 
 			! VARIABLES FOR SPECIES INITIALIZATION 
 INTEGER						         :: DSP
 DOUBLE PRECISION						 :: Davg
 INTEGER,DIMENSION(:),ALLOCATABLE				 :: SP_EX
 CHARACTER(3),DIMENSION(:),ALLOCATABLE				 :: SP_SY
 CHARACTER(3),DIMENSION(:),ALLOCATABLE				 :: SP_CON
 INTEGER,DIMENSION(:),ALLOCATABLE				 :: MAXV_DOF
 DOUBLE PRECISION,DIMENSION(:),ALLOCATABLE		         :: SP_FR
 DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE		         :: SP
 DOUBLE PRECISION,DIMENSION(:,:,:,:),ALLOCATABLE                 :: CARC 
 
 			! VARIABLES FOR BODY AND GAS-SURFACE INTERACTIONS
 INTEGER 							 :: NB,NS,NSE,TNS
 CHARACTER(20) 							 :: BODYNAME
 DOUBLE PRECISION,DIMENSION(:),ALLOCATABLE		         :: BODY_T, BODY_V
 DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE		         :: SURF,SCEN,MNMX
 CHARACTER(20),DIMENSION(:),ALLOCATABLE			         :: GSM
 DOUBLE PRECISION,DIMENSION(:),ALLOCATABLE		         :: Ac_Max
 DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE		         :: Ac_CLLE,Ac_CLLM
 DOUBLE PRECISION,DIMENSION(:),ALLOCATABLE		         :: OVER
 
  			! VARIABLES FOR MOVE
 DOUBLE PRECISION                                                :: CVR,CVM,VR,VRR,VRC(3)
 DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE		         :: CSS,CSS_L,TVIB,SVIB
 DOUBLE PRECISION,DIMENSION(:,:,:),ALLOCATABLE	                 :: CSSP
 DOUBLE PRECISION,DIMENSION(:,:,:),ALLOCATABLE	                 :: CS,SPM
 
  			! VARIABLES FOR COLLISION
 INTEGER,DIMENSION(:,:,:),ALLOCATABLE				 :: IC,ISCG
 INTEGER,DIMENSION(:,:),ALLOCATABLE				 :: IG,COL
 INTEGER,DIMENSION(:),ALLOCATABLE				 :: IR
 INTEGER							 :: CA(2)
 ! VARIABLES FOR INELASTIC COLLISION
 !DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE			 :: RC
 INTEGER							 :: R_FLAG(2) ,V_FLAG(2)
 DOUBLE PRECISION					         :: E_Trans(2),E_Rotat(2),E_Vibra(2),E_Redis,E_Total 
 DOUBLE PRECISION 						 :: RM(2)
   			! VARIABLES FOR OUTPUT
 INTEGER							 :: OPOPT(1:5)
 DOUBLE PRECISION						 :: VELOP(3)
 DOUBLE PRECISION,DIMENSION(:,:,:),ALLOCATABLE	                 :: CSNL
 DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE		         :: CSN
 
 
 !TEST
 INTEGER							 :: SMPC,SMP_PDF,N_PDF,NBINS,rank_PDF
 DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE			 :: BIN
 CHARACTER,DIMENSION(:),ALLOCATABLE			         :: LB_MODEL
 DOUBLE PRECISION						 :: X_PDF,Y_PDF,SPD_MAX
 
!!HEAT FLUX
!!DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE			 :: ETS,ERS,EVS,TRNS_T
DOUBLE PRECISION						 :: ETS,ERS,EVS
DOUBLE PRECISION,DIMENSION(:),ALLOCATABLE			 :: QI,QR,QF,Q_I,Q_R,C_P,C_V,TRNS_T
DOUBLE PRECISION 						 :: CP_EF,CV_EF,GAMM,GASC,DEN_EF,R_STREAM
!!!!REFLECTION INTERNAL ENERGY
DOUBLE PRECISION						 :: ALFA_INT

!!!***  VARIABLES FOR EQULIBIRIUM FLOW ***!!!
 DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE                     :: P_V, PV1
 DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE                     :: B_V  
 DOUBLE PRECISION:: TEMPE

!!!****   KS TesT ***!!!
 INTEGER,DIMENSION(:),ALLOCATABLE		                 :: NMC,CELLSPOT,NMCT,NMCELL
 DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE                     :: VELX,NBIN  
 DOUBLE PRECISION,DIMENSION(:),ALLOCATABLE                       :: MAXV,MINV,CBULK,NEQ_PARAM
 DOUBLE PRECISION 						 :: DELU,KS_CRIT

!!!!!!!!!!!!!!!reaction!!!!!!!!!!!!!!!!!!!
INTEGER,DIMENSION(:),ALLOCATABLE              ::      DISS,QK_part
INTEGER                                       ::      N_REAC,M1,M2,QK_SWITCH
CHARACTER(3)                                  ::      SYM1,SYM2,SYM3,SYM4
DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE   ::TEMP_EXP,COEFF_REAC,E_DISSO,COEF
DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE   ::NUME_EXP,DENO_EXP,INT_MODE,CDT
INTEGER,DIMENSION(:,:),ALLOCATABLE            ::      SYMM_FAC,SWITCH,PDPS

!!!!!!!!!!!!!recombination!!!!!!!!!!!!!!!!!!!!!!!!!
INTEGER,DIMENSION(:,:),ALLOCATABLE            ::      SWITCH_R,PRPS,RPAIR
DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE   ::      RECOM_COEFF,RECOM_TEMP_EXP
CHARACTER(3)                                  ::      SYM5
INTEGER                                       ::      N_RECOM,RCM,MVV,MVV2,A1,A2,DISS_MARK
DOUBLE PRECISION,DIMENSION(:,:,:),ALLOCATABLE   ::      CUMU_PROB

!!!!!!!!!!! EXCHANGE REACTION !!!!!!!!!!!!!!!!!!!!
INTEGER,DIMENSION(:,:),ALLOCATABLE            ::      EXRS
DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE   ::      PEF,TE1,TE2,TE3,ERAE,EXPC,PNET,PDET,ERAEB
INTEGER,DIMENSION(:,:,:),ALLOCATABLE          ::      PRS
DOUBLE PRECISION,DIMENSION(:),ALLOCATABLE     ::      CTEX,Q_VIB
INTEGER                                       ::      COUNT100,COUNT200,EXCH_MARK

END MODULE
