SUBROUTINE MOLDIST
	USE VARIABLES
	INTEGER :: K,IMAX
	DOUBLE PRECISION :: A,B,ERM,NMO_TE,PROBM,ETV,VT(3)
	INTEGER :: MC,MCX,MCY,MSC,MSCX,MSCY
	NM = 0
	NSIM = PSCA*NSIM 
	IF (NSIM.EQ.0) NSIM = 1000000
	ALLOCATE(NMO(1:NSP_T))
	ALLOCATE(PP(10,1:NSIM),MSTAT(1:NSIM),MJETS(1:NSIM),IP(1:NSIM),IR(1:NSIM))
	ALLOCATE(PACKS(1:2,1:NSIM,1:9))
	ALLOCATE(PACKR(1:2,1:NSIM,1:9))
	
	DO 100 L = 1, NSP_T
IF(SP_EX(L).EQ.1)THEN
		REM = 0
		VMP_Local = SQRT(2*BOLTZ*TMP_D/SP(5,L))
		DO 110 	N=1,NC_D
			NMO_TE =	((FND_D*SP_FR(L)*CC(N))/FNUM)+REM 
			NMO(L) = INT(NMO_TE)
			REM = (NMO_TE-NMO(L))
			DO 120  J = 1,NMO(L)
				I = NM + J
				PP(1,I)=CG(1,N)+RF(rank)*(CG(2,N)-CG(1,N))
				PP(2,I)=CG(4,N)+RF(rank)*(CG(5,N)-CG(4,N))
				CALL PCK(PP(1,I),PP(2,I))
				MSCX = ((PP(1,I)-CG(1,N))/CG(3,N))*(NSCX-.001)+1
				MSCY = ((PP(2,I)-CG(4,N))/CG(6,N))*(NSCY-.001)+1
				MSC = (MSCY-1)*NSCX+MSCX+NSCX*NSCY*(MC-1)
				IF (MSC.LT.1) MSC = 1
				IF (MSC.GT.NSC_D) MSC = NSC_D
				IP(I) = MSC
				CALL VMPCAL(VT,VMP_Local,L)
				DO 130 K=1,3
					!CALL RVELC(PP(K+3,I)) 	
					PP(K+3,I)=VT(K)
					!IF(K .LE.2)CALL RVELC(PP(K+3,I),PP(K+4,I),L)
130 				CONTINUE
								GO TO 18
				IF(SP(7,L).EQ.2)THEN
					PP(7,I)=-LOG(RF(rank))*BOLTZ*TMP_D
				ELSE IF(SP(7,L).GT.2) THEN
					A=0.5*SP(7,L)-1.
12	   			ERM=RF(rank)*10.
					B=((ERM/A)**A)*EXP(A-ERM)
					IF (B.LT.RF(rank)) GO TO 12
					PP(7,I)=ERM*BOLTZ*TMP_D
				END IF
				IF(SP(8,L).GT.0) THEN
					!!PP(8,I)=-LOG(RF(rank))*TMP_D/SP(9,L)

				END IF
18				CALL REFINDF(TMP_D,L)
				PP(7,I)=ERS
				PP(8,I)=EVS
				PP(9,I) = L
				MSTAT(I) = 0
		
120 		CONTINUE
		NM = NM + NMO(L)
110	CONTINUE
END IF
100 CONTINUE


	DO 300 L = 1, NSP_T
		DO 310 LL = 1, NSP_T
IF((SP_EX(L).EQ.1).AND.(SP_EX(LL).EQ.1))THEN
			DO 320 N = 1, NC_D
				CARC(1,N,L,LL) = SQRT(BOLTZ*SPM(2,L,LL)/SPM(5,L,LL))*SPM(1,L,LL)
				CARC(2,N,L,LL) = RF(rank)
320		CONTINUE
END IF
310	CONTINUE
300 CONTINUE
IF(rank.EQ.0)WRITE(*,*)"MOLECULAR DISTRIBUTION ...... SUCCESSFUL"
END SUBROUTINE
