SUBROUTINE DIAGNOSTICS
USE VARIABLES
USE MPI
INTEGER :: NCOL_T
DOUBLE PRECISION :: EN_K,EN_R,EN_V,EN_T

INTEGER :: NCOL_TOT,NM_TOT,MOVT_TOT,NC_TOT,RMV_TOT,ENT_TOT,TR_TOT
DOUBLE PRECISION :: EN_K_TOT,EN_R_TOT,EN_V_TOT,EN_T_TOT

        GOTO 200

	NCOL_T = 0
	EN_K   = 0
	EN_R   = 0
	EN_V   = 0
	EN_T   = 0
	DO N=1,NC_D
		NCOL_T = NCOL_T+NCOL(N)
	END DO

	DO I=1,NM
		L=PP(9,I)
		EN_K = EN_K + 0.5*SP(5,L)*(PP(4,I)**2+PP(5,I)**2+PP(6,I)**2)
		EN_R = EN_R + PP(7,I)
		EN_V = EN_V + PP(8,I)*BOLTZ*SP(9,L)
	END DO
	EN_T =(EN_K+EN_R+EN_V)

 200    CONTINUE
	
	CALL MPI_REDUCE(NM,NM_TOT,1,MPI_INTEGER,MPI_SUM,0,MPI_COMM_WORLD,ierr) 
	!CALL MPI_REDUCE(NCOL_T,NCOL_TOT,1,MPI_INTEGER,MPI_SUM,0,MPI_COMM_WORLD,ierr)
	CALL MPI_REDUCE(NC_D,NC_TOT,1,MPI_INTEGER,MPI_SUM,0,MPI_COMM_WORLD,ierr)  
	CALL MPI_REDUCE(MOVT,MOVT_TOT,1,MPI_INTEGER,MPI_SUM,0,MPI_COMM_WORLD,ierr) 
	CALL MPI_REDUCE(RMV,RMV_TOT,1,MPI_INTEGER,MPI_SUM,0,MPI_COMM_WORLD,ierr)
	CALL MPI_REDUCE(ENT,ENT_TOT,1,MPI_INTEGER,MPI_SUM,0,MPI_COMM_WORLD,ierr)
	CALL MPI_REDUCE(CountTR,TR_TOT,1,MPI_INTEGER,MPI_SUM,0,MPI_COMM_WORLD,ierr)
	!CALL MPI_REDUCE(EN_K,EN_K_TOT,1,MPI_DOUBLE_PRECISION,MPI_SUM,0,MPI_COMM_WORLD,ierr)
	!CALL MPI_REDUCE(EN_R,EN_R_TOT,1,MPI_DOUBLE_PRECISION,MPI_SUM,0,MPI_COMM_WORLD,ierr)
	!CALL MPI_REDUCE(EN_V,EN_V_TOT,1,MPI_DOUBLE_PRECISION,MPI_SUM,0,MPI_COMM_WORLD,ierr)
	!CALL MPI_REDUCE(EN_T,EN_T_TOT,1,MPI_DOUBLE_PRECISION,MPI_SUM,0,MPI_COMM_WORLD,ierr)
	
	IF (rank.EQ.0) THEN
		
		WRITE(13,*)"Time Step No : ",NPR," Out of ", NTS(2)
		
		WRITE(13,*)"	Simulated Particles      	  : ",NM_TOT
		
		!WRITE(*,*)"	No.of Cells		      	  : ",NCX_D,NCY_D,NC_TOT
		!WRITE(*,*)"	No. of Collisions/Step   	  : ",NCOL_TOT
		!WRITE(*,*)"	Kinetic Energy in Domain 	  : ",EN_K_TOT
		!WRITE(*,*)"	Rot. Energy in Domain 	  	  : ",EN_R_TOT
		!WRITE(*,*)"	Vib. Energy in Domain 		  : ",EN_V_TOT
		!WRITE(*,*)"	Total Energy in Domain 		  : ",EN_T_TOT
		!WRITE(*,*)"	Molecular Moves         	  : ",MOVT_TOT
		!WRITE(*,*)"	Molecules Ent,Rem,Net	    	  : ",ENT_TOT,RMV_TOT-TR_TOT,ENT_TOT-RMV_TOT+TR_TOT
		!WRITE(*,*)
		!WRITE(13,*)NPR,NM_TOT,NCOL_TOT,EN_K_TOT,EN_R_TOT,EN_V_TOT,EN_T_TOT,RMV_TOT
	END IF
END SUBROUTINE
