SUBROUTINE REFCOND(I,X1,Y1,X2,Y2)
USE VARIABLES
INTEGER			  :: I
DOUBLE PRECISION :: X1,Y1,X2,Y2
DOUBLE PRECISION :: MINX,MAXX,MINY,MAXY
DOUBLE PRECISION :: A,B,C,DET
DOUBLE PRECISION :: RVEL,DIN

	SE = 0
	MINX = MIN(X1,X2)
	MAXX = MAX(X1,X2)
	MINY = MIN(Y1,Y2)
	MAXY = MAX(Y1,Y2)
	A	  = Y2-Y1
	B 	  = X2-X1
	C	  = B*Y1-A*X1
	RVEL = SQRT(PP(4,I)**2+PP(5,I)**2)
	DO 100 K = 1,TNS
		DET = SURF(5,K)*B-A*SURF(6,K)	
		IF(DET.NE.0.) THEN
			XC = (SURF(6,K)*C-B*SURF(7,K))/DET
			YC = (SURF(5,K)*C-A*SURF(7,K))/DET
			IF(((XC-MNMX(1,K)).GE.-TOL).AND.((XC-MNMX(2,K)).LE.TOL).AND. &
				((YC-MNMX(3,K)).GE.-TOL).AND.((YC-MNMX(4,K)).LE.TOL).AND. &
				((XC-MINX).GE.-TOL).AND.((XC-MAXX).LE.TOL).AND. &
				((YC-MINY).GE.-TOL).AND.((YC-MAXY).LE.TOL))THEN
					DIN = SQRT(((XC-X2)**2+(YC-Y2)**2))
					AT  = DIN/RVEL
					SE	 = K
					KK  = BD(SE) 
					FLAG(4) = 1
					RETURN
			END IF
		END IF
100 CONTINUE
END SUBROUTINE
