SUBROUTINE REFINDF(T,L)
USE VARIABLES
INTEGER :: L
DOUBLE PRECISION :: T
ERS = 0
EVS = 0

IF(SP_NA(L) .GT. 1) CALL ROTE(T,L)

IF(SP(8,L) .GT. 0) CALL VIBE(T,L)
END SUBROUTINE

SUBROUTINE ROTE(T,L)
USE VARIABLES
INTEGER :: L
DOUBLE PRECISION :: T,W,F,FMAX_R
FMAX_R = (((0.50*SP(7,L))-1)/2.718282)**((0.50*SP(7,L))-1)
IF (SP(7,L) .GT. 2) THEN
1	W = 10.0*RF(rank)
   	F = W**(SP(7,L)/2.-1.) *EXP(-W)
       IF (RF(rank).GT. F/FMAX_R) GOTO 1
ELSE
   	W=-ALOG(RF(rank))
END IF   	
	ERS = BOLTZ*T*W
!WRITE(111,*)W,ERS,T
END SUBROUTINE


SUBROUTINE VIBE(T,L)
USE VARIABLES
INTEGER :: L
DOUBLE PRECISION :: W,F,FMAX_V,T,DOF
DOF = (2.0 * SP(9,L)/T)/(EXP(SP(9,L)/T)-1)
FMAX_V = (((0.50*DOF)-1)/2.718282)**((0.50*DOF)-1)
IF (DOF .GT. 2) THEN
1	W = 3.0*DOF*RF(rank)
   	F = W**(DOF/2.-1.) *EXP(-W)
       IF (RF(rank).GT. F/FMAX_V) GOTO 1
ELSE
   	W=-ALOG(RF(rank))*0.5*DOF
END IF   	
	EVS = 0.5*BOLTZ*T*W

END SUBROUTINE

  
     
