SUBROUTINE ADAPREPORT
USE VARIABLES
OPEN(12,FILE="2.7.Adaptation Report.dat",FORM="FORMATTED",ACCESS="APPEND")
WRITE(12,*)LVL,NC_OLD,NC_D
    DO 100 N=1,NC_OLD
	WRITE(12,*)CG(1,N),CG(4,N),CAR(N)
100 CONTINUE
CLOSE(12)
END SUBROUTINE
