SUBROUTINE OCOLLS(N,L,LL,NSEL)
USE VARIABLES	
INTEGER :: N,L,LL,NSEL

IF (NSEL.GT.0) THEN
	FLAG(5) = 1
	IF((L.NE.LL).AND.(IC(2,N,L).LT.1.OR.IC(2,N,LL).LT.1))THEN
		FLAG(5) = 0
	END IF
	IF((L.EQ.LL).AND.(IC(2,N,LL).LT.2)) THEN
		FLAG(5) = 0
	END IF
END IF
RETURN
END SUBROUTINE
