SUBROUTINE SCOLLS(N,L,LL)
USE VARIABLES	
INTEGER :: N,L,LL
INTEGER :: MC,MSC
DOUBLE PRECISION :: B,CVR1,CVR2,CVR3,Gaf

NSTR = 0
NSGR = 0
INC = 0
B = RF(rank)
	K=INT(B*(IC(2,N,L)-0.0001))+IC(1,N,L)+1 	
	CA(1)=IR(K) 				
5  MSC=IP(CA(1)) 

	CALL NNEIGH(N,MSC,L,LL)

	B=	RF(rank)
	K=INT(B*(ISCG(2,MSC,LL)-0.0001))+ISCG(1,MSC,LL)+1 
	CA(2)=IR(K) 
	IF(CA(1).EQ.CA(2)) THEN
		GO TO 5 	
	END IF
	
	
	DO 100 K=1,3
		VRC(K)=PP(K+3,CA(1))-PP(K+3,CA(2)) 			
100 CONTINUE
	VRR=VRC(1)**2+VRC(2)**2+VRC(3)**2
	VR=SQRT(VRR)
	Gaf = GAM(2.5-SPM(3,L,LL))
	CVR1=VR*SPM(1,L,LL)/Gaf	
	CVR2=(2.*BOLTZ*SPM(2,L,LL)/(SPM(5,L,LL)*VRR))
	CVR3=SPM(3,L,LL)-0.5
	CVR=CVR1*CVR2**CVR3
RETURN
END SUBROUTINE

SUBROUTINE NNEIGH(N,MSC,L,LL)
USE VARIABLES
INTEGER :: NSTR,NSGR,INC
INTEGER :: MSC,N,L,LL
	IF((L.EQ.LL.AND.ISCG(2,MSC,LL).EQ.1).OR.(L.NE.LL.AND.ISCG(2,MSC,LL).EQ.0)) THEN
		NSTR=1
		NSGR=1
6     INC=NSGR*NSTR
		NSGR=-NSGR
		NSTR=NSTR+1 
		MSC=MSC+INC 			
		IF (MSC.LT.1.OR.MSC.GT.NSC_D) GO TO 6 	
			IF (ISC(MSC).NE.N.OR.ISCG(2,MSC,LL).LT.1)THEN
				GO TO 6
			END IF
	END IF
RETURN
END SUBROUTINE
