SUBROUTINE VHS(CP,CQ,CR)
USE VARIABLES
DOUBLE PRECISION ::A,B,C
DOUBLE PRECISION ::CP,CQ,CR
	B=2.*RF(rank)-1.				
	A=SQRT(1.-B*B)
	C=2.*PI*RF(rank)				
	CP=B*VR
	CQ=A*COS(C)*VR
	CR=A*SIN(C)*VR
RETURN
END SUBROUTINE

