SUBROUTINE ECOLLS(N)
USE VARIABLES	
DOUBLE PRECISION ::VRCP(3),VCCM(3),RMM,RML
      L = PP(9,CA(1))
      LL = PP(9,CA(2))
      RML=SPM(5,L,LL)/SP(5,LL)
      RMM=SPM(5,L,LL)/SP(5,L)
      DO 100 K=1,3
        VCCM(K)=RML*PP(K+3,CA(1))+RMM*PP(K+3,CA(2))
	VRCP(K)=0
100   CONTINUE

	IF(ABS(SPM(4,L,LL)-1.).LT.1.E-3) THEN 	
		CALL VHS(VRCP(1),VRCP(2),VRCP(3))
	ELSE 					
		CALL VSS(VRCP(1),VRCP(2),VRCP(3))
	END IF

	DO 200 K=1,3
		PP(K+3,CA(1))=VCCM(K)+RMM*VRCP(K) 
		PP(K+3,CA(2))=VCCM(K)-RML*VRCP(K) 
200 CONTINUE
END SUBROUTINE




