SUBROUTINE VSS(CP,CQ,CR)
USE VARIABLES
DOUBLE PRECISION ::A,B,C,D,OC,SIC
DOUBLE PRECISION ::CP,CQ,CR
	B=2.*(RF(rank)**SPM(4,L,LL))-1.			
	A=SQRT(1.-B*B)
	C=2.*PI*RF(rank)				
	OC=COS(C)
	SIC=SIN(C)
	D=SQRT(VRC(2)**2+VRC(3)**2)
	IF(D.GT.1.E-6) THEN
		CP=B*VRC(1)+A*SIC*D
		CQ=B*VRC(2)+A*(VR*VRC(3)*OC-VRC(1)*VRC(2)*SIC)/D
		CR=B*VRC(3)-A*(VR*VRC(2)*OC+VRC(1)*VRC(3)*SIC)/D
	ELSE
		CP=B*VRC(1)
		CQ=A*OC*VRC(2)
		CR=A*SIC*VRC(3)
	END IF
RETURN
END SUBROUTINE
