SUBROUTINE FINALPOSITION
USE VARIABLES
 CHARACTER(10) :: FPre
 CHARACTER(3) :: FSuf
 
	 FPre = 'z-3.2.Fina'
 	WRITE(FSuf,'(I3.3)')rank
OPEN(Rank+1,FILE=FPre//FSuf//'.dat',FORM="FORMATTED")
	 DO 100 I =1, NM
		WRITE(Rank+1,*)PP(1,I),PP(2,I),I
100 CONTINUE
CLOSE(Rank+1)


END SUBROUTINE
