SUBROUTINE VELBINNING
 USE VARIABLES
INTEGER :: B,P,Q
DOUBLE PRECISION :: SPD,DEL

	DEL = SPD_MAX/NBINS
	DO B=1,NBINS
		IF(B.EQ.1)THEN
BIN(1,B)=0
		ELSE
BIN(1,B)=BIN(2,B-1)
END IF
		BIN(2,B)= BIN(1,B)+DEL
		IF(B.EQ.NBINS)BIN(2,B)=SPD_MAX
END DO

OPEN(13,FILE="3.3.Vel Distribution.dat",FORM="FORMATTED")

 	OPEN(21,FILE="2.9.Vbin.dat",FORM="FORMATTED")

DO 150 Q = 1, SMPC
	READ(21,*)SPD
	DO B=1,NBINS
		IF((SPD.GT.BIN(1,B)).AND.(SPD.LE.BIN(2,B)))THEN
			BIN(3,B)=BIN(3,B)+1
		END IF
	END DO
150 CONTINUE
	DO B=1,NBINS
		WRITE(13,*)(BIN(1,B)+BIN(2,B))/2,BIN(3,B)
	END DO

 	

CLOSE(13)
END SUBROUTINE
