SUBROUTINE MACROSP
 USE VARIABLES
 INTEGER 		  :: Q
 DOUBLE PRECISION :: A,UU,TRI
 DOUBLE PRECISION :: NDEN,DEN,PRES,MACH
 DOUBLE PRECISION :: Kn
 DOUBLE PRECISION :: TTEM,RTEM,VTEM,ToTEM
 DOUBLE PRECISION :: TDOF,RDOF,VDOF,TEMP1(nc_D)
 !!DOUBLE PRECISION :: CP_EF,CV_EF,TOTD,GAMM,M,GASC
 CHARACTER(10) :: FPre
 CHARACTER(3) :: FSuf
 CHARACTER(13)		:: StringN
  
	DO 100 N=1,NC_D	
		DO 110 Q=1,14
			DO 120 L=1,NSP_T
				CSNL(Q,N,L) = 0
120 		CONTINUE
110 	CONTINUE
100 CONTINUE
DO L=1,NSP_T
	C_V(L)=0
	C_P(L)=0
END DO
TOTD=0
 CP_EF =0
 CV_EF=0
 
DO L=1,NSP_T
	GASC =(8.31446)/(SP(5,L)*6.022E+23) 
	FSP = SP_FR(L)
	C_V(L)=GASC/(SP(6,L)-1)					!!ADD GAS CONSTANT
	C_P(L)=C_V(L)+GASC
	CV_EF=CV_EF+C_V(L)*FSP*SP(5,L)
	CP_EF = CP_EF + C_P(L)*FSP*SP(5,L)
	TOTD = TOTD + FSP*SP(5,L)
END DO
	DEN_EF =  TOTD * FND_J(1)
	CV_EF=CV_EF/TOTD
	CP_EF = CP_EF/TOTD 	
	R_STREAM = CP_EF - CV_EF
	GAMM = CP_EF/CV_EF



	DO 200 N=1,NC_D	
		DO 210 L=1,NSP_T 
			CSNL(1,N,L) = CSNL(1,N,L)+CS(1,N,L)
			CSNL(2,N,L) = CSNL(2,N,L)+(SP(5,L)*CS(1,N,L))

			DO 211 K=3,5
				CSNL(K,N,L)   = CSNL(K,N,L)+SP(5,L)*CS(K-1,N,L)
				CSNL(K+3,N,L) = CSNL(K+3,N,L)+SP(5,L)*CS(K+2,N,L)
211    	CONTINUE
			CSNL(9,N,L)  = CSNL(9,N,L)+(CSNL(6,N,L)+CSNL(7,N,L)+CSNL(8,N,L))			
			CSNL(10,N,L) = CSNL(10,N,L)+CS(8,N,L)
			CSNL(11,N,L) = CSNL(11,N,L)+SP(7,L)*CS(1,N,L)
			CSNL(12,N,L) = CSNL(12,N,L)+TVIB(N,L)*SVIB(N,L)*CS(1,N,L)
			CSNL(13,N,L) = LOG(CS(10,N,L)/CS(11,N,L)) !!CSNL(13,N,L)+SVIB(N,L)*CS(1,N,L)	
			CSNL(14,N,L) = CSNL(14,N,L)+CS(12,N,L)	
210 	CONTINUE
200 CONTINUE

FPre = 'z-3.6.Flsp'
WRITE(FSuf,'(I3.3)')rank

	DO 300 L=1,NSP_T 
	  IF(SP_EX(L).EQ.1)THEN
		OPEN (L+rank+10,FILE=FPre//FSuf//SP_SY(L)//'.dat',FORM='FORMATTED',ACCESS="APPEND")
			
DO 800 N=1,NC_D
			A=FNUM/(CC(N)*NSMP)
			IF(CC(N).EQ.0)A = 0
			DO 810 K=1,3
				VELOP(K) = CSNL(K+2,N,L)/CSNL(2,N,L)	
810		CONTINUE		
	  
			NDEN = CSNL(1,N,L)*A
			DEN  = NDEN*CSNL(2,N,L)/CSNL(1,N,L)
			UU	  = VELOP(1)**2+VELOP(2)**2+VELOP(3)**2
			
			TTEM = (CSNL(9,N,L)-(CSNL(2,N,L)*UU))/(3*BOLTZ*CSNL(1,N,L))
			TDOF = 3
			IF(L.eq.1)TEMP1(n) =TTEM
			TTEM = (TEMP1(n)+ TTEM)*0.5 
			
			IF(CSNL(11,N,L).NE.0) THEN
				RTEM = (2/BOLTZ)*CSNL(10,N,L)/CSNL(11,N,L)
				RDOF = CSNL(11,N,L)/CSNL(1,N,L)
			ELSE
				RTEM = 0
				RDOF = 0
			END IF
			
			IF(CSNL(13,N,L).NE.0) THEN
				VTEM = 3351/CSNL(13,N,L) !!CSNL(12,N,L)/CSNL(13,N,L)
				!!VDOF = CSNL(13,N,L)/CSNL(1,N,L)
				VDOF = (2*CSNL(14,N,L))/(BOLTZ*VTEM*CSNL(1,N,L))
			ELSE
				VTEM = 0
				VDOF = 0
			END IF
			
			ToTEM= ((TDOF*TTEM)+(RDOF*RTEM)+(VDOF*VTEM))/(TDOF+RDOF+VDOF)
		!	R_STREAM = (NSMP*BOLTZ)/CSNL(2,N,L)
			
			PRES = DEN*R_STREAM*ToTEM
			MACH=SQRT(VELOP(1)**2+VELOP(2)**2+VELOP(3)**2)/SQRT((GAMM*R_STREAM*ToTEM))	!!FOR SINGLE SPECIES		
			
						
			XC = 0.5*(CG(1,N)+CG(2,N))
			YC = 0.5*(CG(4,N)+CG(5,N))

		WRITE(L+rank+10,*)XC,YC,VELOP(1:3),DEN,NDEN,PRES,TTEM,RTEM,VTEM,ToTEM,MACH

800 CONTINUE


		CLOSE(L+rank+10)
END IF
300 CONTINUE
END SUBROUTINE

