SUBROUTINE PARAINIT
USE VARIABLES
USE MPI

	CALL MPI_INIT(ierr)
	CALL MPI_COMM_SIZE(MPI_COMM_WORLD, nprocs,ierr)
	CALL MPI_COMM_RANK(MPI_COMM_WORLD, rank,ierr)
	
	ALLOCATE(SD_C(1:nprocs),SD_N(1:nprocs))
END SUBROUTINE
