SUBROUTINE VELCOLLECTION
USE VARIABLES
DOUBLE PRECISION :: MAX_V,MIN_V
INTEGER :: BINN,TOTB,I,N,J

MIN_V = -10000.0
MAX_V = 10000.0
TOTB = (MAX_V-MIN_V)/DELU

DO I=1,NM
	MSC = IP(I)
	MC  = ISC(MSC)
	IF (NMC(MC) .EQ. 1000) THEN
		N = MC
		CBULK(N)=CBULK(N)/NMC(N)

		DO J=1,NMC(N)
			VELX(J,N) = VELX(J,N)-CBULK(N)
			IF(VELX(J,N).GT.MIN_V .AND. VELX(J,N) .LT. MAX_V) THEN
				BINN = (-MIN_V/DELU)+VELX(J,N)/DELU
				IF(BINN .LT. 1)BINN=1
		        	NBIN(N,BINN) = NBIN(N,BINN)+1
			END IF
		END DO	
		NMCT(N) = NMCT(N) + NMC(N)
		NMC(N) = 0
		CBULK(N) = 0.0d0
	ELSE
		NMC(MC)=NMC(MC)+1
		VELX(NMC(MC),MC)=PP(4,I)
		CBULK(MC)=CBULK(MC)+PP(4,I)
	END IF
END DO

END SUBROUTINE
